export const API_LOADING = "API_LOADING";

export const BUDGET_LIST_SUCCESS = "BUDGET_LIST_SUCCESS";
export const BUDGET_LIST_FAILED = "BUDGET_LIST_FAILED";

export const BUDGET_DETAILS_SUCCESS = "BUDGET_DETAILS_SUCCESS";
export const BUDGET_DETAILS_FAILED = "BUDGET_DETAILS_FAILED";

